export const gameStore = [
    {
        id: 101,
        name: "God of War",
        price: 90,
        releaseDate: "2018",
        rating: 9,
        description: "Join Kratos and his son on a mythic Norse adventure.",
        img: "god-of-war.jpg",
    },
    {
        id: 102,
        name: "Witcher 3",
        price: 110,
        releaseDate: "2015",
        rating: 9.2,
        description: "Award-winning RPG in a vast, monster-filled fantasy world.",
        img: "witcher.jpg",
    },
    {
        id: 103,
        name: "Metal Gear Solid 3",
        price: 70,
        releaseDate: "2004",
        rating: 9.2,
        description: "Stealth action classic. Espionage in the Cold War era.",
        img: "mgs3.jpg",
    },
    {
        id: 104,
        name: "Skyrim",
        price: 69,
        releaseDate: "2011",
        rating: 9.1,
        description:
            "Epic open world RPG filled with dragons, magic, and adventure.",
        img: "The_Elder_Scrolls_V.jpg",
    },
    {
        id: 105,
        name: "NFS Most Wanted",
        price: 43,
        releaseDate: "2005",
        rating: 8.4,
        description: "Classic NFS action with street racing and police chases.",
        img: "Need_for_Speed_Most_Wanted.jpg",
    },
    {
        id: 106,
        name: "Oblivion Remastered",
        price: 200,
        releaseDate: "2025",
        rating: 6.1,
        description: "Return to Cyrodiil in this modern remake of the classic RPG.",
        img: "oblivion.jpg",
    },
    {
        id: 107,
        name: "Cs2",
        price: 0,
        releaseDate: "2023",
        rating: 8.6,
        description: "The next generation of the legendary tactical shooter.",
        img: "counter-strike-2.jpg",
    },
    {
        id: 108,
        name: "Jedi Survivior",
        price: 85,
        releaseDate: "2023",
        rating: 7.5,
        description: "Survive and fight as a Jedi in a galaxy far, far away.",
        img: "jedi-survivor.jpg",
    },
    {
        id: 109,
        name: "ET Game",
        price: 40,
        releaseDate: "1982",
        rating: 1,
        description: "Infamous Atari game. Notorious for its role in game history.",
        img: "Etgame.jpg",
    },
    {
        id: 110,
        name: "Red Dead Redemption",
        price: 120,
        releaseDate: "2010",
        rating: 9,
        description: "Epic wild west open world adventure and storytelling.",
        img: "Red_Dead_Redemption.jpg",
    },
    {
        id: 111,
        name: "Euro Truck Sim.2",
        price: 70,
        releaseDate: "2012",
        rating: 9.8,
        description: "Drive trucks and deliver cargo across Europe.",
        img: "ets2.jpg",
    },
    {
        id: 112,
        name: "Undertale",
        price: 47,
        releaseDate: "2015",
        rating: 10,
        description: "Beloved indie RPG filled with heart, humor, and choices.",
        img: "undertale.jpg",
    },
];